### ISSUE TITLE
sequelize.import is not a function

### ISSUE THREAD

**Issue by rociodemula** [bjrmatos/sequelize-auto-import#9]
Hi all,

We found a problem using this package with Sequelize since .import is [deprecated](https://sequelize.org/master/manual/models-definition.html#:~:text=Deprecated%3A%20sequelize.,import&text=import%20.,single%20file%20using%20the%20sequelize.)

We solved with a patch in src/index.js by adding the following require:
```
Sequelize = require('sequelize')
```

and change the sequelize.import call in line 147 by this:
```
model = require(pathFile, function(seqInstance, Datatypes) {
    return defineCall(seqInstance, Datatypes, {
      schema: schema,
      schemaName: schema || '',
      modelName: modelName,
      // for now pass the tableName in snake case,
      // when this module is on npm we should create an option
      // to control this behaviour
      tableName: tableName,
      completeTableName: completeTableName,
      separator: SEPARATOR
    });
  })(sequelize, Sequelize);
```
After this, it works fine with Sequelize 6.3.0. Could you please be so kind to consider as a PR?

Thanks in advance!

**Comment by rociodemula** [comment]
Code patch included as pull request
